import { Sizes } from "./sizes";

export const Themes = {
    Primary: 'primary',
    Secondary: 'secondary',
    Tertiary: 'tertiary',
    Info: 'info',
    Highlight: 'highlight',
    Success: 'success',
    Warning: 'warning',
    Alert: 'alert',
    Danger: 'danger',
    Light: 'light',
    Dark: 'dark',
};

export type Themes = typeof Themes[keyof typeof Themes];

export const ThemeClasses = {
    Background: {
        [Themes.Primary]: 'bg-primary-500',
        [Themes.Secondary]: 'bg-secondary-500',
        [Themes.Tertiary]: 'bg-tertiary-500',
        [Themes.Info]: 'bg-info-500',
        [Themes.Highlight]: 'bg-highlight-500',
        [Themes.Success]: 'bg-success-500',
        [Themes.Warning]: 'bg-warning-500',
        [Themes.Alert]: 'bg-alert-500',
        [Themes.Danger]: 'bg-danger-500',
        [Themes.Light]: 'bg-light-500',
        [Themes.Dark]: 'bg-dark-500',
    },
    Text: {
        [Themes.Primary]: 'text-primary-500',
        [Themes.Secondary]: 'text-secondary-500',
        [Themes.Tertiary]: 'text-tertiary-500',
        [Themes.Info]: 'text-info-500',
        [Themes.Highlight]: 'text-highlight-500',
        [Themes.Success]: 'text-success-500',
        [Themes.Warning]: 'text-warning-500',
        [Themes.Alert]: 'text-alert-500',
        [Themes.Danger]: 'text-danger-500',
        [Themes.Light]: 'text-light-500',
        [Themes.Dark]: 'text-dark-500',
    },
    Button: {
        Base: 'ya-btn',
        Disabled: 'ya-btn-disabled',
        Block: 'ya-btn-block',
        Close: 'ya-btn-close',
        Sizes: {
            [Sizes.Smallest]: 'ya-btn-2xs',
            [Sizes.Smaller]: 'ya-btn-xs',
            [Sizes.Small]: 'ya-btn-sm',
            [Sizes.Medium]: 'ya-btn-md',
            [Sizes.Large]: 'ya-btn-lg',
            [Sizes.Larger]: 'ya-btn-xl',
            [Sizes.Largest]: 'ya-btn-2xl',
        },
        Active: {
            Outline: {
                [Themes.Primary]: 'ya-btn-primary-outline-active',
                [Themes.Secondary]: 'ya-btn-secondary-outline-active',
                [Themes.Tertiary]: 'ya-btn-tertiary-outline-active',
                [Themes.Info]: 'ya-btn-info-outline-active',
                [Themes.Highlight]: 'ya-btn-highlight-outline-active',
                [Themes.Success]: 'ya-btn-success-outline-active',
                [Themes.Warning]: 'ya-btn-warning-outline-active',
                [Themes.Alert]: 'ya-btn-alert-outline-active',
                [Themes.Danger]: 'ya-btn-danger-outline-active',
                [Themes.Light]: 'ya-btn-light-outline-active',
                [Themes.Dark]: 'ya-btn-dark-outline-active',
            },
            [Themes.Primary]: 'ya-btn-primary-active',
            [Themes.Secondary]: 'ya-btn-secondary-active',
            [Themes.Tertiary]: 'ya-btn-tertiary-active',
            [Themes.Info]: 'ya-btn-info-active',
            [Themes.Highlight]: 'ya-btn-highlight-active',
            [Themes.Success]: 'ya-btn-success-active',
            [Themes.Warning]: 'ya-btn-warning-active',
            [Themes.Alert]: 'ya-btn-alert-active',
            [Themes.Danger]: 'ya-btn-danger-active',
            [Themes.Light]: 'ya-btn-light-active',
            [Themes.Dark]: 'ya-btn-dark-active',
        },
        Outline: {
            [Themes.Primary]: 'ya-btn-primary-outline',
            [Themes.Secondary]: 'ya-btn-secondary-outline',
            [Themes.Tertiary]: 'ya-btn-tertiary-outline',
            [Themes.Info]: 'ya-btn-info-outline',
            [Themes.Highlight]: 'ya-btn-highlight-outline',
            [Themes.Success]: 'ya-btn-success-outline',
            [Themes.Warning]: 'ya-btn-warning-outline',
            [Themes.Alert]: 'ya-btn-alert-outline',
            [Themes.Danger]: 'ya-btn-danger-outline',
            [Themes.Light]: 'ya-btn-light-outline',
            [Themes.Dark]: 'ya-btn-dark-outline',
        },
        [Themes.Primary]: 'ya-btn-primary',
        [Themes.Secondary]: 'ya-btn-secondary',
        [Themes.Tertiary]: 'ya-btn-tertiary',
        [Themes.Info]: 'ya-btn-info',
        [Themes.Highlight]: 'ya-btn-highlight',
        [Themes.Success]: 'ya-btn-success',
        [Themes.Warning]: 'ya-btn-warning',
        [Themes.Alert]: 'ya-btn-alert',
        [Themes.Danger]: 'ya-btn-danger',
        [Themes.Light]: 'ya-btn-light',
        [Themes.Dark]: 'ya-btn-dark',
    },
    IconButton: {
        Base: 'ya-i-btn',
        Disabled: 'ya-btn-disabled',
        Sizes: {
            [Sizes.Smallest]: 'ya-i-btn-2xs',
            [Sizes.Smaller]: 'ya-i-btn-xs',
            [Sizes.Small]: 'ya-i-btn-sm',
            [Sizes.Medium]: 'ya-i-btn-md',
            [Sizes.Large]: 'ya-i-btn-lg',
            [Sizes.Larger]: 'ya-i-btn-xl',
            [Sizes.Largest]: 'ya-i-btn-2xl',
        },
        Active: {
            Outline: {
                [Themes.Primary]: 'ya-i-btn-primary-outline-active',
                [Themes.Secondary]: 'ya-i-btn-secondary-outline-active',
                [Themes.Tertiary]: 'ya-i-btn-tertiary-outline-active',
                [Themes.Info]: 'ya-i-btn-info-outline-active',
                [Themes.Highlight]: 'ya-i-btn-highlight-outline-active',
                [Themes.Success]: 'ya-i-btn-success-outline-active',
                [Themes.Warning]: 'ya-i-btn-warning-outline-active',
                [Themes.Alert]: 'ya-i-btn-alert-outline-active',
                [Themes.Danger]: 'ya-i-btn-danger-outline-active',
                [Themes.Light]: 'ya-i-btn-light-outline-active',
                [Themes.Dark]: 'ya-i-btn-dark-outline-active',
            },
            [Themes.Primary]: 'ya-i-btn-primary-active',
            [Themes.Secondary]: 'ya-i-btn-secondary-active',
            [Themes.Tertiary]: 'ya-i-btn-tertiary-active',
            [Themes.Info]: 'ya-i-btn-info-active',
            [Themes.Highlight]: 'ya-i-btn-highlight-active',
            [Themes.Success]: 'ya-i-btn-success-active',
            [Themes.Warning]: 'ya-i-btn-warning-active',
            [Themes.Alert]: 'ya-i-btn-alert-active',
            [Themes.Danger]: 'ya-i-btn-danger-active',
            [Themes.Light]: 'ya-i-btn-light-active',
            [Themes.Dark]: 'ya-i-btn-dark-active',
        },
        Outline: {
            [Themes.Primary]: 'ya-i-btn-primary-outline',
            [Themes.Secondary]: 'ya-i-btn-secondary-outline',
            [Themes.Tertiary]: 'ya-i-btn-tertiary-outline',
            [Themes.Info]: 'ya-i-btn-info-outline',
            [Themes.Highlight]: 'ya-i-btn-highlight-outline',
            [Themes.Success]: 'ya-i-btn-success-outline',
            [Themes.Warning]: 'ya-i-btn-warning-outline',
            [Themes.Alert]: 'ya-i-btn-alert-outline',
            [Themes.Danger]: 'ya-i-btn-danger-outline',
            [Themes.Light]: 'ya-i-btn-light-outline',
            [Themes.Dark]: 'ya-i-btn-dark-outline',
        },
        [Themes.Primary]: 'ya-i-btn-primary',
        [Themes.Secondary]: 'ya-i-btn-secondary',
        [Themes.Tertiary]: 'ya-i-btn-tertiary',
        [Themes.Info]: 'ya-i-btn-info',
        [Themes.Highlight]: 'ya-i-btn-highlight',
        [Themes.Success]: 'ya-i-btn-success',
        [Themes.Warning]: 'ya-i-btn-warning',
        [Themes.Alert]: 'ya-i-btn-alert',
        [Themes.Danger]: 'ya-i-btn-danger',
        [Themes.Light]: 'ya-i-btn-light',
        [Themes.Dark]: 'ya-i-btn-dark',
    },
};