import { Sizes } from "./sizes";

export const Themes = {
    Primary: 'primary',
    Secondary: 'secondary',
    Tertiary: 'tertiary',
    Info: 'info',
    Highlight: 'highlight',
    Success: 'success',
    Warning: 'warning',
    Alert: 'alert',
    Danger: 'danger',
    Light: 'light',
    Dark: 'dark',
}

export type Themes = typeof Themes[keyof typeof Themes];

export const ThemeClasses = {
    Background: {
        [Themes.Primary]: 'bg-primary-500',
        [Themes.Secondary]: 'bg-secondary-500',
        [Themes.Tertiary]: 'bg-tertiary-500',
        [Themes.Info]: 'bg-info-500',
        [Themes.Highlight]: 'bg-highlight-500',
        [Themes.Success]: 'bg-success-500',
        [Themes.Warning]: 'bg-warning-500',
        [Themes.Alert]: 'bg-alert-500',
        [Themes.Danger]: 'bg-danger-500',
        [Themes.Light]: 'bg-light-500',
        [Themes.Dark]: 'bg-dark-500',
    },
    Text: {
        [Themes.Primary]: 'text-primary-500',
        [Themes.Secondary]: 'text-secondary-500',
        [Themes.Tertiary]: 'text-tertiary-500',
        [Themes.Info]: 'text-info-500',
        [Themes.Highlight]: 'text-highlight-500',
        [Themes.Success]: 'text-success-500',
        [Themes.Warning]: 'text-warning-500',
        [Themes.Alert]: 'text-alert-500',
        [Themes.Danger]: 'text-danger-500',
        [Themes.Light]: 'text-light-500',
        [Themes.Dark]: 'text-dark-500',
    },
    Button: {
        Sizes: {
            [Sizes.Smallest]: 'px-1 py-0.5 text-xs',
            [Sizes.Smaller]: 'px-2 py-1 text-sm',
            [Sizes.Small]: 'px-3 py-1.5 text-sm',
            [Sizes.Medium]: 'px-4 py-2 text-base',
            [Sizes.Large]: 'px-5 py-2.5 text-base',
            [Sizes.Larger]: 'px-7 py-3.5 text-lg',
            [Sizes.Largest]: 'px-9 py-4.5 text-xl',
        },
        Base: 'round border transition duration-200 ease-in-out',
        Disabled: 'opacity-50 cursor-not-allowed',
        ReadOnly: 'opacity-50 cursor-not-allowed',
        [Themes.Primary]: 'text-light bg-primary-500 border-primary-600 outline-primary-500/50 hover:bg-primary-600 focus:border-primary-500/50 focus:outline-3',
        [Themes.Secondary]: 'text-light bg-secondary-500 border-secondary-600 outline-secondary-500/50 hover:bg-secondary-600 focus:border-secondary-500/50 focus:outline-3',
        [Themes.Tertiary]: 'text-light bg-tertiary-500 border-tertiary-600 outline-tertiary-500/50 hover:bg-tertiary-600 focus:border-tertiary-500/50 focus:outline-3',
        [Themes.Info]: 'text-light bg-info-500 border-info-600 outline-info-500/50 hover:bg-info-600 focus:border-info-500/50 focus:outline-3',
        [Themes.Highlight]: 'text-light bg-highlight-500 border-highlight-600 outline-highlight-500/50 hover:bg-highlight-600 focus:border-highlight-500/50 focus:outline-3',
        [Themes.Success]: 'text-light bg-success-500 border-success-600 outline-success-500/50 hover:bg-success-600 focus:border-success-500/50 focus:outline-3',
        [Themes.Warning]: 'text-dark bg-warning-500 border-warning-600 outline-warning-500/50 hover:bg-warning-600 focus:border-warning-500/50 focus:outline-3',
        [Themes.Alert]: 'text-light bg-alert-500 border-alert-600 outline-alert-500/50 hover:bg-alert-600 focus:border-alert-500/50 focus:outline-3',
        [Themes.Danger]: 'text-light bg-danger-500 border-danger-600 outline-danger-500/50 hover:bg-danger-600 focus:border-danger-500/50 focus:outline-3',
        [Themes.Light]: 'text-dark bg-light-500 border-light-600 outline-light-500/50 hover:bg-light-600 focus:border-light-500/50 focus:outline-3',
        [Themes.Dark]: 'text-light bg-dark-500 border-dark-600 outline-dark-500/50 hover:bg-dark-600 focus:border-dark-500/50 focus:outline-3',
        Outline: {
            [Themes.Primary]: 'text-primary-500 bg-transparent border-primary-500 outline-primary-500/50 hover:bg-primary-100 focus:border-primary-500/50 focus:outline-3',
            [Themes.Secondary]: 'text-secondary-500 bg-transparent border-secondary-500 outline-secondary-500/50 hover:bg-secondary-100 focus:border-secondary-500/50 focus:outline-3',
            [Themes.Tertiary]: 'text-tertiary-500 bg-transparent border-tertiary-500 outline-tertiary-500/50 hover:bg-tertiary-100 focus:border-tertiary-500/50 focus:outline-3',
            [Themes.Info]: 'text-info-500 bg-transparent border-info-500 outline-info-500/50 hover:bg-info-100 focus:border-info-500/50 focus:outline-3',
            [Themes.Highlight]: 'text-highlight-500 bg-transparent border-highlight-500 outline-highlight-500/50 hover:bg-highlight-100 focus:border-highlight-500/50 focus:outline-3',
            [Themes.Success]: 'text-success-500 bg-transparent border-success-500 outline-success-500/50 hover:bg-success-100 focus:border-success-500/50 focus:outline-3',
            [Themes.Warning]: 'text-warning-500 bg-transparent border-warning-500 outline-warning-500/50 hover:bg-warning-100 focus:border-warning-500/50 focus:outline-3',
            [Themes.Alert]: 'text-alert-500 bg-transparent border-alert-500 outline-alert-500/50 hover:bg-alert-100 focus:border-alert-500/50 focus:outline-3',
            [Themes.Danger]: 'text-danger-500 bg-transparent border-danger-500 outline-danger-500/50 hover:bg-danger-100 focus:border-danger-500/50 focus:outline-3',
            [Themes.Light]: 'text-light-500 bg-transparent border-light-500 outline-light-500/50 hover:bg-light-100 focus:border-light-500/50 focus:outline-3',
            [Themes.Dark]: 'text-dark-500 bg-transparent border-dark-500 outline-dark-500/50 hover:bg-dark-100 focus:border-dark-500/50 focus:outline-3',
        }
    },
    Panel: {
        [Themes.Primary]: 'bg-primary-100 border-primary-500',
        [Themes.Secondary]: 'bg-secondary-100 border-secondary-500',
        [Themes.Tertiary]: 'bg-tertiary-100 border-tertiary-500',
        [Themes.Info]: 'bg-info-100 border-info-500',
        [Themes.Highlight]: 'bg-highlight-100 border-highlight-500',
        [Themes.Success]: 'bg-success-100 border-success-500',
        [Themes.Warning]: 'bg-warning-100 border-warning-500',
        [Themes.Alert]: 'bg-alert-100 border-alert-500',
        [Themes.Danger]: 'bg-danger-100 border-danger-500',
        [Themes.Light]: 'bg-light-100 border-light-500',
        [Themes.Dark]: 'bg-dark-100 border-dark-500',
    },
    Alert: {
        [Themes.Primary]: 'text-primary-700 bg-primary-100 border-primary-500',
        [Themes.Secondary]: 'text-secondary-700 bg-secondary-100 border-secondary-500',
        [Themes.Tertiary]: 'text-tertiary-700 bg-tertiary-100 border-tertiary-500',
        [Themes.Info]: 'text-info-700 bg-info-100 border-info-500',
        [Themes.Highlight]: 'text-highlight-700 bg-highlight-100 border-highlight-500',
        [Themes.Success]: 'text-success-700 bg-success-100 border-success-500',
        [Themes.Warning]: 'text-warning-700 bg-warning-100 border-warning-500',
        [Themes.Alert]: 'text-alert-700 bg-alert-100 border-alert-500',
        [Themes.Danger]: 'text-danger-700 bg-danger-100 border-danger-500',
        [Themes.Light]: 'text-light-700 bg-light-100 border-light-500',
        [Themes.Dark]: 'text-dark-700 bg-dark-100 border-dark-500',
    },
    Bag: {
        [Themes.Primary]: 'bag-primary',
        [Themes.Secondary]: 'bag-secondary',
        [Themes.Tertiary]: 'bag-tertiary',
        [Themes.Info]: 'bag-info',
        [Themes.Highlight]: 'bag-highlight',
        [Themes.Success]: 'bag-success',
        [Themes.Warning]: 'bag-warning',
        [Themes.Alert]: 'bag-alert',
        [Themes.Danger]: 'bag-danger',
        [Themes.Light]: 'bag-light',
        [Themes.Dark]: 'bag-dark',
    },
    Badge: {
        [Themes.Primary]: 'badge-primary',
        [Themes.Secondary]: 'badge-secondary',
        [Themes.Tertiary]: 'badge-tertiary',
        [Themes.Info]: 'badge-info',
        [Themes.Highlight]: 'badge-highlight',
        [Themes.Success]: 'badge-success',
        [Themes.Warning]: 'badge-warning',
        [Themes.Alert]: 'badge-alert',
        [Themes.Danger]: 'badge-danger',
        [Themes.Light]: 'badge-light',
        [Themes.Dark]: 'badge-dark',
    },
    Tag: {
        [Themes.Primary]: 'tag-primary',
        [Themes.Secondary]: 'tag-secondary',
        [Themes.Tertiary]: 'tag-tertiary',
        [Themes.Info]: 'tag-info',
        [Themes.Highlight]: 'tag-highlight',
        [Themes.Success]: 'tag-success',
        [Themes.Warning]: 'tag-warning',
        [Themes.Alert]: 'tag-alert',
        [Themes.Danger]: 'tag-danger',
        [Themes.Light]: 'tag-light',
        [Themes.Dark]: 'tag-dark',
    },
    Accordion: {
        [Themes.Primary]: 'accordion-primary',
        [Themes.Secondary]: 'accordion-secondary',
        [Themes.Tertiary]: 'accordion-tertiary',
        [Themes.Info]: 'accordion-info',
        [Themes.Highlight]: 'accordion-highlight',
        [Themes.Success]: 'accordion-success',
        [Themes.Warning]: 'accordion-warning',
        [Themes.Alert]: 'accordion-alert',
        [Themes.Danger]: 'accordion-danger',
        [Themes.Light]: 'accordion-light',
        [Themes.Dark]: 'accordion-dark',
    },
    Progress: {
        [Themes.Primary]: 'progress-primary',
        [Themes.Secondary]: 'progress-secondary',
        [Themes.Tertiary]: 'progress-tertiary',
        [Themes.Info]: 'progress-info',
        [Themes.Highlight]: 'progress-highlight',
        [Themes.Success]: 'progress-success',
        [Themes.Warning]: 'progress-warning',
        [Themes.Alert]: 'progress-alert',
        [Themes.Danger]: 'progress-danger',
        [Themes.Light]: 'progress-light',
        [Themes.Dark]: 'progress-dark',
    },
};