namespace RoyalCode.Razor.Styles;

public enum ZIndexes
{
    Default,
    Zero,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,
    Ten,
    Twenty,
    Thirty,
    Forty,
    Fifty,
    Sixty,
    Seventy,
    Eighty,
    Ninety,
    Hundred,
    SevenHundred,
    EightHundred,
    NineHundred,
    NineHundredTen,
    NineHundredTwenty,
    NineHundredThirty,
    NineHundredForty,
    NineHundredFifty,
    NineHundredSixty,
    NineHundredSeventy,
    NineHundredEighty,
    NineHundredNinety,
    OneThousand,
    TwoThousand,
    ThreeThousand,
    FourThousand,
    FiveThousand,
    TenThousand,
    OneHundredThousand,
    NineHundredThousand,
    NineHundredTenThousand,
    NineHundredTwentyThousand,
    NineHundredThirtyThousand,
    NineHundredFortyThousand,
    NineHundredFiftyThousand,
    NineHundredSixtyThousand,
    NineHundredSeventyThousand,
    NineHundredEightyThousand,
    NineHundredNinetyThousand,
    OneMillion,
    TwoMillion,
    ThreeMillion,
    FourMillion,
    FiveMillion,
    TenMillion,
    OneHundredMillion,
    OneBillion
}

public static class ZIndexesExtensions
{
    public static string ToCssClass(this ZIndexes zIndex)
    {
        return zIndex switch
        {
            ZIndexes.Default => string.Empty,
            ZIndexes.Zero => "z-0",
            ZIndexes.One => "z-1",
            ZIndexes.Two => "z-2",
            ZIndexes.Three => "z-3",
            ZIndexes.Four => "z-4",
            ZIndexes.Five => "z-5",
            ZIndexes.Six => "z-6",
            ZIndexes.Seven => "z-7",
            ZIndexes.Eight => "z-8",
            ZIndexes.Nine => "z-9",
            ZIndexes.Ten => "z-10",
            ZIndexes.Twenty => "z-20",
            ZIndexes.Thirty => "z-30",
            ZIndexes.Forty => "z-40",
            ZIndexes.Fifty => "z-50",
            ZIndexes.Sixty => "z-60",
            ZIndexes.Seventy => "z-70",
            ZIndexes.Eighty => "z-80",
            ZIndexes.Ninety => "z-90",
            ZIndexes.Hundred => "z-100",
            ZIndexes.SevenHundred => "z-700",
            ZIndexes.EightHundred => "z-800",
            ZIndexes.NineHundred => "z-900",
            ZIndexes.NineHundredTen => "z-910",
            ZIndexes.NineHundredTwenty => "z-920",
            ZIndexes.NineHundredThirty => "z-930",
            ZIndexes.NineHundredForty => "z-940",
            ZIndexes.NineHundredFifty => "z-950",
            ZIndexes.NineHundredSixty => "z-960",
            ZIndexes.NineHundredSeventy => "z-970",
            ZIndexes.NineHundredEighty => "z-980",
            ZIndexes.NineHundredNinety => "z-990",
            ZIndexes.OneThousand => "z-1000",
            ZIndexes.TwoThousand => "z-2000",
            ZIndexes.ThreeThousand => "z-3000",
            ZIndexes.FourThousand => "z-4000",
            ZIndexes.FiveThousand => "z-5000",
            ZIndexes.TenThousand => "z-10000",
            ZIndexes.OneHundredThousand => "z-100000",
            ZIndexes.NineHundredThousand => "z-900000",
            ZIndexes.NineHundredTenThousand => "z-910000",
            ZIndexes.NineHundredTwentyThousand => "z-920000",
            ZIndexes.NineHundredThirtyThousand => "z-930000",
            ZIndexes.NineHundredFortyThousand => "z-940000",
            ZIndexes.NineHundredFiftyThousand => "z-950000",
            ZIndexes.NineHundredSixtyThousand => "z-960000",
            ZIndexes.NineHundredSeventyThousand => "z-970000",
            ZIndexes.NineHundredEightyThousand => "z-980000",
            ZIndexes.NineHundredNinetyThousand => "z-990000",
            ZIndexes.OneMillion => "z-1000000",
            ZIndexes.TwoMillion => "z-2000000",
            ZIndexes.ThreeMillion => "z-3000000",
            ZIndexes.FourMillion => "z-4000000",
            ZIndexes.FiveMillion => "z-5000000",
            ZIndexes.TenMillion => "z-10000000",
            ZIndexes.OneHundredMillion => "z-100000000",
            ZIndexes.OneBillion => "z-1000000000",
        };
    }
}
